//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace SBS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
        [ScaffoldColumn(false)]
        public int ID { get; set; }
        [Required(ErrorMessage = "Please enter name"), MaxLength(50)]
        [DataType(DataType.Text)]
        [Display(Name = "Full Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter Address"), MaxLength(250)]
        [Display(Name = "Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please enter Zipcode"), MaxLength(10)]
        [Display(Name = "ZipCode")]
        public string Zipcode { get; set; }
        [Required(ErrorMessage = "Please enter Contact"), MaxLength(15)]
        [Display(Name = "Contact")]
        public string Contact { get; set; }
        [Required(ErrorMessage = "Please enter HomeContact"), MaxLength(15)]
        [Display(Name = "HomeContact")]
        public string HomeContact { get; set; }
        [Display(Name = "Email address")]
        [Required(ErrorMessage = "The email address is required")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail id is not valid")]
        public string EmailID { get; set; }
        [Required(ErrorMessage = "Please enter your issue"), MaxLength(250)]
        [Display(Name = "Issue")]
        public string Problem { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicle> Vehicles { get; set; }
    }
}
