//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        public int ID { get; set; }
        public string DealerName { get; set; }
        public string DealerNumber { get; set; }
        public string Address { get; set; }
        public string Zipcode { get; set; }
        public string EmailID { get; set; }
        public string Contact { get; set; }
    }
}
